BoroHFR/ViewModels/Authentication/ConfirmEmailViewModel.cs
namespace BoroHFR.ViewModels.Authentication;

public class ConfirmEmailViewModel
{
    public string Username { get; set; }
    public Uri ConfirmUrl { get; set; }
}

BoroHFR/ViewModels/Authentication/EmailConfirmationNotificationViewModel.cs
namespace BoroHFR.ViewModels.Authentication;

public class EmailConfirmationNotificationViewModel
{
    public string EmailAddress { get; set; }
}

BoroHFR/ViewModels/Authentication/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoroHFR.ViewModels.Authentication;

public class LoginViewModel
{
    [Required(ErrorMessage = "Add meg a felhasználóneved!")]
    [MinLength(3, ErrorMessage = "A felhasználónevek minimum 3 karakter hosszúak.")]
    [MaxLength(20, ErrorMessage = "A felhasználónevek maximum 20 karakter hosszúak.")]
    [DataType(DataType.Text)]
    public string Username { get; set; }
    [Required(ErrorMessage = "Add meg a jelszavad!")]
    [MinLength(8, ErrorMessage = "A jelszavak minimum 8 karakterből állnak.")]
    [DataType(DataType.Password)]
    public string Password { get; set; }
    public bool RemainLoggedIn { get; set; }
    public bool BadUsername { get; set; }
    public bool BadPassword { get; set; }
}

BoroHFR/ViewModels/Authentication/NewPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoroHFR.ViewModels.Authentication;

public class NewPasswordViewModel
{
    [Required(ErrorMessage = "Kérlek add meg az új jelszavad!")]
    [MinLength(8, ErrorMessage = "A jelszónak minimum 8 karakter hosszúnak kell lennie.")]
    public string NewPassword { get; set; }
    [Required(ErrorMessage = "Kérlek add meg még egyszer a jelszót.")]
    [Compare(nameof(NewPassword), ErrorMessage = "A jelszavak nem egyeznek.")]
    public string NewPasswordAgain { get; set; }
}

BoroHFR/ViewModels/Authentication/PasswordResetEmailSentViewModel.cs
namespace BoroHFR.ViewModels.Authentication;

public class PasswordResetEmailSentViewModel
{
    public string EMail { get; set; }
}

BoroHFR/ViewModels/Authentication/PasswordResetRequestViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoroHFR.ViewModels.Authentication;

public class PasswordResetRequestViewModel
{
    [Required(ErrorMessage = "A mező kitöltése kötelező.")]
    [EmailAddress(ErrorMessage = "Kérlek adj meg egy érvényes e-mail címet.")]
    public string EMail { get; set; }
}

BoroHFR/ViewModels/Authentication/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoroHFR.ViewModels.Authentication;

public class RegisterViewModel
{
    [DataType(DataType.Text)]
    [MinLength(3, ErrorMessage = "A minimális hossz 3.")]
    [MaxLength(20, ErrorMessage = "A maximális hossz 20.")]
    [Required(ErrorMessage = "Kérlek adj meg egy felhasználónevet!")]
    public string Username { get; set; }
    [Required(ErrorMessage = "Kérlek adj meg egy jelszót!")]
    [MinLength(8, ErrorMessage = "A jelszónak minimum 8 karaktert kell tartalmaznia.")]
    [DataType(DataType.Password)]
    public string Password { get; set; }

    [Required(ErrorMessage = "Kérlek add meg még egyszer a jelszót!")]
    [Compare(nameof(Password), ErrorMessage = "A megadott jelszavak nem egyeznek.")]
    public string PasswordAgain { get; set; }

    [Required(ErrorMessage = "Kérlek adj meg egy e-mail címet, melyen elérhető vagy! (Nem küldünk felesleges e-maileket.)")]
    [EmailAddress(ErrorMessage = "Kérlek adj meg egy érvényes e-mail címet.")]
    public string EMail { get; set; }
    [DataType(DataType.Text)]
    [Required(ErrorMessage = "A regisztrációhoz add meg a meghívó kódod!")]
    public string Token { get; set; }
    public bool AcceptPrivacyPolicy { get; set; }

    public bool UsernameTaken { get; set; }
    public bool EMailTaken { get; set; }
    public bool BadToken { get; set; }
    public bool DidNotAcceptPrivacyPolicy { get; set; }
}

BoroHFR/ViewModels/Authentication/ResetPasswordViewModel.cs
namespace BoroHFR.ViewModels.Authentication;

public class ResetPasswordViewModel
{
    public string Username { get; set; }
    public Uri ResetUrl { get; set; }
}

BoroHFR/ViewModels/SysAdmin/ResetPasswordViewModel.cs
using BoroHFR.Models;

namespace BoroHFR.ViewModels.SysAdmin
{
    public class ResetPasswordViewModel
    {
        public bool Confirmed { get; set; }
        public string Password { get; set; }
        public User User { get; set; }
    }
}

BoroHFR/Controllers/AuthenticationController.cs
using System.Security.Claims;
using BoroHFR.Controllers.Helpers;
using BoroHFR.Data;
using BoroHFR.Models;
using BoroHFR.Services;
using BoroHFR.ViewModels.Authentication;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoroHFR.Controllers;

[AllowAnonymous]
[Route("authentication")]
public class AuthenticationController : Controller
{
    private readonly BoroHfrDbContext _dbContext;
    private readonly EmailService _emailService;
    private readonly ILogger<AuthenticationController> _logger;
    private readonly IConfiguration _configuration;

    public AuthenticationController(BoroHfrDbContext dbContext,
        EmailService emailService,
        ILogger<AuthenticationController> logger,
        IConfiguration configuration)
    {
        _dbContext = dbContext;
        _emailService = emailService;
        _logger = logger;
        _configuration = configuration;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return RedirectToAction("Login");
    }

    [HttpGet("contributors")]
    public IActionResult Contributors()
    {
        return View();
    }

    [HttpGet("login")]
    public IActionResult Login()
    {
        return User?.Identity?.IsAuthenticated ?? false ? RedirectToAction("Index","Home") : View();
    }

    [HttpPost("login/{returnUrl?}")]
    public async Task<IActionResult> Login(LoginViewModel model, string? returnUrl)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var user = await _dbContext.Users.FirstOrDefaultAsync(x=>x.Username == model.Username);
        if (user is null)
        {
            model.BadUsername = true;
            return View(model);
        }

        if (!BCrypt.Net.BCrypt.EnhancedVerify(model.Password, user.PasswordHash))
        {
            model.BadPassword = true;
            return View(model);
        }

        //check e-mail confirmed
        if (!user.EMailConfirmed)
        {
            if (!await _dbContext.EmailConfirmationTokens
                    .Where(x=>!x.Used && x.ValidUntil > DateTimeOffset.UtcNow && x.User == user)
                    .AnyAsync())
            {
                try
                {
                    await this.SendVerificationEmailAsync(_dbContext, _emailService, user);
                }
                catch (Exception)
                {
                    return StatusCode(500, "Email error - consult operators if persists");
                }
                 
            }
           
            return View("EmailConfirmationNotification", new EmailConfirmationNotificationViewModel() { EmailAddress = SafeEmailString(user.EMail) });
        }

        var (principal, properties) = GetAuthenticationData(user,model.RemainLoggedIn);

        if (returnUrl is null)
        {
            properties.RedirectUri = Url.Action("Index","Home");
        }
        
        return SignIn(principal, properties,
            Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
    }

    [HttpGet("register")]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost("register")]
    public async Task<IActionResult> Register(RegisterViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        //privacy policy check
        if (!model.AcceptPrivacyPolicy)
        {
            model.DidNotAcceptPrivacyPolicy = true;
        }

        //check username availability
        if (await _dbContext.Users.AnyAsync(x=>x.Username == model.Username))
        {
            model.UsernameTaken = true;
        }
        //check email availability
        if (await _dbContext.Users.AnyAsync(x=>x.EMail == model.EMail))
        {
            model.EMailTaken = true;
        }

        //return error if email or username taken
        if (model.UsernameTaken || model.EMailTaken || model.DidNotAcceptPrivacyPolicy)
        {
            return View(model);

        }
        //check token validity
        var invToken = await _dbContext.InviteTokens
            .Include(token=>token.Class)
            .Where(x=>x.Token == model.Token && x.ValidUntil > DateTimeOffset.UtcNow)
            .FirstOrDefaultAsync();
        if (invToken is null)
        {
            model.BadToken = true;
            return View(model);
        }
        else if (invToken.Usages <= 0 || DateTimeOffset.UtcNow > invToken.ValidUntil)
        {
            model.BadToken = true;
            return View(model);
        }


        //store new user in database and set token as used
        var user = new User()
        {
            ClassId = invToken.ClassId,
            EMail = model.EMail,
            PasswordHash = BCrypt.Net.BCrypt.EnhancedHashPassword(model.Password),
            Role = invToken.Role,
            Username = model.Username,
            Class = invToken.Class,
            RegisterTime = DateTimeOffset.UtcNow,
        };
        

        _dbContext.Users.Add(user);

        invToken.Usages--;


        //email verification
        await this.SendVerificationEmailAsync(_dbContext, _emailService, user);
        
        await _dbContext.SaveChangesAsync();
        return View("EmailConfirmationNotification", new EmailConfirmationNotificationViewModel() { EmailAddress = SafeEmailString(user.EMail) });
    }

    [HttpGet("logout")]
    public IActionResult Logout()
    {
        return SignOut(new AuthenticationProperties() { RedirectUri = Url.Action("Login") }, Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
    }

    [HttpGet("passwordreset")]
    public IActionResult ResetPassword()
    {
        return View();
    }

    [HttpPost("passwordreset")]
    public async Task<IActionResult> ResetPassword(PasswordResetRequestViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var user = await _dbContext.Users.FirstOrDefaultAsync(x=>x.EMail == model.EMail);
        if (user is not null)
        {
            try
            {
                await this.SendPasswordResetEmailAsync(_dbContext, _emailService, user);
            }
            catch (Exception e)
            {
                return StatusCode(500, "Email error - consult operators if persists");
            }
            
        }
        return View("PasswordResetEmailSent", new PasswordResetEmailSentViewModel() { EMail = SafeEmailString(model.EMail) });
    }

    [HttpGet("newpassword")]
    public async Task<IActionResult> NewPassword(PasswordResetTokenId token)
    {
        var resToken = await _dbContext.PasswordResetTokens
            .Where(x=>!x.Used && x.ValidUntil > DateTimeOffset.UtcNow && x.Token==token)
            .FirstOrDefaultAsync();
        if (resToken is null)
        {
            return View("NewPasswordFailed");
        }
        return View();

    }

    [HttpPost("newpassword")]
    public async Task<IActionResult> NewPassword(PasswordResetTokenId token, NewPasswordViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        var resToken = await _dbContext.PasswordResetTokens
            .Where(x=>!x.Used && x.ValidUntil > DateTimeOffset.UtcNow && x.Token==token)
            .Include(t=>t.User)
            .FirstOrDefaultAsync();
        if (resToken is null)
        {
            return View("NewPasswordFailed");
        }

        var user = resToken.User;
        user.PasswordHash = BCrypt.Net.BCrypt.EnhancedHashPassword(model.NewPassword);
        resToken.Used = true;

        await _dbContext.SaveChangesAsync();

        return View("NewPasswordSuccess");
    }

    private string SafeEmailString(string email)
    {
        return email.Substring(0, email.IndexOf('@') / 3) + "***" + email.Substring(email.IndexOf('@') - 2);
    }

    [HttpGet("confirmemail")]
    public async Task<IActionResult> ConfirmEmail(EmailConfirmationTokenId token)
    {
        var cToken = await _dbContext.EmailConfirmationTokens
            .Where(x=>!x.Used && x.ValidUntil > DateTimeOffset.UtcNow && x.Token==token)
            .Include(t=>t.User)
            .FirstOrDefaultAsync();
        if (cToken is null)
        {
            return View("EmailConfirmationFailed");
        }
        var user = cToken.User;
        user.EMailConfirmed = true;
        cToken.Used = true;
        await _dbContext.SaveChangesAsync();
        return View("EmailConfirmationSuccess");
    }

    private (ClaimsPrincipal principal, AuthenticationProperties properties) GetAuthenticationData(User u, bool persistentLogin)
    {
        var claims = new List<Claim>()
        {
            new Claim(ClaimTypes.Name, u.Username),
            new Claim(ClaimTypes.Email, u.EMail),
            new Claim(ClaimTypes.Role,u.Role.ToString()),
            new Claim("Id",u.Id.value.ToString())
        };
        var identity = new ClaimsIdentity(claims, Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
        var principal = new ClaimsPrincipal(identity);
        var authSettings = new AuthenticationProperties
        {
            IsPersistent = persistentLogin,
            ExpiresUtc = persistentLogin ? DateTimeOffset.UtcNow.AddMonths(1) : DateTimeOffset.UtcNow.AddHours(1),
            AllowRefresh = true
        };
        return (principal, authSettings);
    }
}

BoroHFR/Views/Authentication/Contributors.cshtml
@{
    ViewData["Title"] = "Közreműködők";
}

<partial name="_ContributorsPartial"></partial>
<a class="" href='@Url.Action("Login","Authentication")'>Vissza a bejelentkezéshez</a>

BoroHFR/Views/Authentication/EmailConfirmationFailed.cshtml
@model string

@{
    ViewData["Title"] = "E-mail cím megerősítés sikertelen";
}

<h1>E-mail cím megerősítése sikertelen</h1>
<p>A megerősítő kód érvénytelen.</p>
<p>A folytatáshoz kérlek, jelentkezz be!</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/EmailConfirmationNotification.cshtml
@model BoroHFR.ViewModels.Authentication.EmailConfirmationNotificationViewModel

@{
    ViewData["Title"] = "E-mail cím megerősítés";
}

<h1>Kérlek erősítsd meg a megadott e-mail címet!</h1>
<p>Küldtünk egy e-mailt a megadott címre (@Model.EmailAddress).</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/EmailConfirmationSuccess.cshtml
@{
    ViewData["Title"] = "E-mail cím visszajelzés";
}

<h1>E-mail cím sikeresen megerősítve</h1>
<p>A folytatáshoz kérlek, jelentkezz be!</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/Login.cshtml
@model BoroHFR.ViewModels.Authentication.LoginViewModel

@{
    ViewData["Title"] = "Bejelentkezés";
}

@using (Html.BeginForm(FormMethod.Post, new
{
    @class = "px-5 coolform",
}))
{
    <h1>Bejelentkezés</h1>
    <div class="form-group py-1">
    <label class="form-label">Felhasználónév:</label>
    @Html.TextBoxFor(x => x.Username, null, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.Username, "", new
    {
    @class = "text-danger"
    })
    @if (Model is not null && Model.BadUsername)
        {
            <span class="text-danger">Érvénytelen felhasználónév.</span>
        }
    </div>
    <div class="form-group py-1">
    <label class="form-label">Jelszó:</label>
    @Html.PasswordFor(x => x.Password, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.Password, "", new
    {
    @class = "text-danger"
    })
    @if (Model is not null && Model.BadPassword)
        {
            <span class="text-danger">Hibás jelszó.</span>
            <br />
            <span>Elfelejtetted a jelszavad? <a href='@Url.Action("ResetPassword")'>Jelszó visszaállítása</a></span>
        }
    </div>
    <div class="form-check py-1">
    @Html.CheckBoxFor(m=>m.RemainLoggedIn, new {@class="form-check-input", @id="remainloggedinbox"})
    <label class="form-check-label" for="remainloggedinbox">Bejelentkezve maradok</label>
</div>
    <button class="btn btn-primary" type="submit">Bejelentkezés</button>
    <p class="mt-1 text-center mb-0">Nincs fiókod? <a asp-action="Register" class="fw-bold">Regisztrálj!</a></p>
}

BoroHFR/Views/Authentication/NewPassword.cshtml
@model BoroHFR.ViewModels.Authentication.NewPasswordViewModel

@{
    ViewData["Title"] = "Jelszómódosítás";
}

<h2>Jelszómódosítás</h2>
@using(Html.BeginForm(FormMethod.Post))
{
    <div class="form-group py-1">
        <label>Új jelszó:</label>
        @Html.PasswordFor(m=>m.NewPassword,new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.NewPassword,null,new {@class="text-danger"})
    </div>
    <div class="form-group py-1">
        <label>Új jelszó ismét:</label>
        @Html.PasswordFor(m=>m.NewPasswordAgain,new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.NewPasswordAgain,null,new {@class="text-danger"})
    </div>
    <button type="submit" class="btn btn-primary">Mentés</button>
}

BoroHFR/Views/Authentication/NewPasswordFailed.cshtml
@{
    ViewData["Title"] = "Változás értesítés";
}

@model string
<h1>Jelszó visszaállítása sikertelen</h1>
<p>A megadott kód érvénytelen.</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/NewPasswordSuccess.cshtml
@{
    ViewData["Title"] = "Változás értesítés";
}

<h1>A jelszó megváltozott</h1>
<p>A folytatáshoz kérlek, jelentkezz be!</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/PasswordResetEmailSent.cshtml
@model BoroHFR.ViewModels.Authentication.PasswordResetEmailSentViewModel

@{
    ViewData["Title"] = "Visszaállítás értésítés";
}

<h1>Jelszó visszaállítása</h1>
<p>Küldtünk egy e-mailt a megadott címre (@Model.EMail).</p>
<a class="btn btn-primary" href='@Url.Action("Login","Authentication")'>Bejelentkezés</a>

BoroHFR/Views/Authentication/Register.cshtml
@model BoroHFR.ViewModels.Authentication.RegisterViewModel

@{
    ViewData["Title"] = "Regisztráció";
}

@using (Html.BeginForm(FormMethod.Post, new
{
    @class = "px-5 coolform"
}))
{
    <h1>Regisztráció</h1>
    <div class="form-group py-1">
    <label>Meghívó kód:</label>
    @Html.TextBoxFor(x => x.Token, null, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.Token, "", new
    {
    @class = "text-danger"
    })
    @if (Model is not null && Model.BadToken)
        {
            <span class="text-danger">Érvénytelen meghívó kód.</span>
        }
    </div>
    <div class="form-group py-1">
    <label>Felhasználónév:</label>
    @Html.TextBoxFor(x => x.Username, null, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.Username, "", new
    {
    @class = "text-danger"
    })
    @if (Model is not null && Model.UsernameTaken)
        {
            <span class="text-danger">A megadott felhasználónév foglalt.</span>
        }
    </div>
    <div class="form-group py-1">
    <label>Jelszó:</label>
    @Html.PasswordFor(x => x.Password, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.Password, "", new
    {
    @class = "text-danger"
    })
</div>
    <div class="form-group py-1">
    <label>Jelszó megerősítése:</label>
    @Html.PasswordFor(x => x.PasswordAgain, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.PasswordAgain, "", new
    {
    @class = "text-danger"
    })
</div>
    <div class="form-group py-1">
    <label>E-mail:</label>
    @Html.TextBoxFor(x => x.EMail, null, new {@class="form-control bg-dark text-light", @required=""})
    @Html.ValidationMessageFor(x => x.EMail, "", new
    {
    @class = "text-danger"
    })
    @if (Model is not null && Model.EMailTaken)
        {
            <span class="text-danger">A megadott e-mail címmel már regisztráltak.</span>
        }
    </div>

    <div class="form-check py-1">
    @Html.CheckBoxFor(m=>m.AcceptPrivacyPolicy,new {@id="privpolbox",@class="form-check-input",@required=""})
    <label for="privpolbox" class="form-check-label">Elfogadom az <a href="#" role="button" data-bs-toggle="modal"
            data-bs-target="#privacypolicymodal">adatvédelmi irányelvek</a>et.</label>
    <br />
    @if (Model is not null && Model.DidNotAcceptPrivacyPolicy)
        {
            <span class="text-danger">Az adatvédelmi irányelvek elfogadása kötelező.</span>
        }
    </div>
    <button class="btn btn-primary" type="submit">Regisztráció</button>

    <p class="text-center mb-0 mt-1">Van már fiókod? <a asp-action="Login" class="fw-bold">Jelentkezz be!</a></p>
}

@section Modals
    {
    <partial name="_PrivacyPolicyModal" />
}

BoroHFR/Views/Authentication/ResetPassword.cshtml
@model BoroHFR.ViewModels.Authentication.PasswordResetRequestViewModel

@{
    ViewData["Title"] = "Jelszó visszaállítás";
}

<h2>Jelszó visszaállítása</h2>

<p>
    A jelszó visszaállításához add meg az e-mail címed.<br/>
    Ha a megadott e-mail címmel van regisztrált fiók, küldünk egy linket, melyen módosíthatod a jelszavad.
</p>

@using(Html.BeginForm(FormMethod.Post)){
    <div class="form-group py-1">
        @Html.TextBoxFor(m=>m.EMail ,null,new {@class="form-control"})
        @Html.ValidationMessageFor(m=>m.EMail)
    </div>
    <button type="submit" class="btn btn-primary my-2">Küldés</button>
}

BoroHFR/Views/Authentication/_Layout.cshtml
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BHR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoroHFR.styles.css" asp-append-version="true" />
    <style>
        html,
        body {
            min-height: 100%;
            height: 100%;
        }
    </style>
</head>

<body class="bg-black text-light">


    <div class="verticalcenter py-5 justify-content-center">
        <div class="mx-3 mx-sm-auto p-3 bg-dark my-auto" style="height: fit-content; border-radius: 15px;">
            @RenderBody()
        </div>

    </div>

    <footer class="text-center footer text-muted">
        <p class="m-0 p-2">BoroHFR - &copy; 2023-@DateTime.Today.Year Jávor Márton, Varga-Labóczki Vazul, Szabó Tamás</p>
    </footer>

    @await RenderSectionAsync("Modals", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>