BoroHFR/Controllers/ButtonGameController.cs
using BoroHFR.Controllers.Helpers;
using BoroHFR.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoroHFR.Controllers
{
    [Route("button")]
    [Authorize("User")]
    public class ButtonGameController : Controller
    {
        private readonly BoroHfrDbContext _dbContext;

        public ButtonGameController(BoroHfrDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await _dbContext.Users.FirstAsync(x=>x.Id == this.GetUserId());

            return View(user.ButtonGameClicks);
        }

        [HttpGet("click")]
        public async Task<IActionResult> Click()
        {
            var user = await _dbContext.Users.FirstAsync(x => x.Id == this.GetUserId());
            user.ButtonGameClicks++;
            await _dbContext.SaveChangesAsync();
            return Ok(user.ButtonGameClicks);
        }
    }
}

BoroHFR/Views/ButtonGame/Index.cshtml
@model ulong

<h1 class="text-center">Eddig <span id="clickCount">@Model</span> alkalommal nyomtad meg a gombot.</h1>
<div class="d-flex">
    <button class="btn btn-primary mx-auto" onmouseup="buttonClick()">Nyomj meg!</button>
</div>



@section Scripts {
    <script>
        async function buttonClick() {
            var res = await fetch("@Url.Action("Click", "ButtonGame")");
            var cnt = await res.text();
            document.getElementById('clickCount').innerHTML = cnt;
        }
    </script>
}