BoroHFR/Controllers/GroupsController.cs
using BoroHFR.Controllers.Helpers;
using BoroHFR.Data;
using BoroHFR.ViewModels.Groups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoroHFR.Controllers;

[Authorize("User")]
[Route("groups")]
public class GroupsController : Controller
{
    private readonly BoroHfrDbContext dbContext;

    public GroupsController(BoroHfrDbContext dbContext)
    {
        this.dbContext = dbContext;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var uid = this.GetUserId();
        var user = await dbContext.Users.Include(x => x.Groups).Include(x => x.Class).FirstAsync(x => x.Id == uid);
        IndexViewModel VM = new IndexViewModel() { Groups = await dbContext.Groups.Where(x => x.Members.Contains(user) || x.Id == user.Class.DefaultGroupId).ToArrayAsync() };
        return View(VM);
    }
}

BoroHFR/Controllers/TasksController.cs
using BoroHFR.Controllers.Helpers;
using BoroHFR.Data;
using BoroHFR.ViewModels.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BoroHFR.Controllers
{
    [Route("tasks")]
    [Authorize("User")]
    public class TasksController : Controller
    {
        private readonly BoroHfrDbContext _dbContext;

        public TasksController(BoroHfrDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            var user = await _dbContext.Users.Include(x=>x.Class).FirstAsync(x=>x.Id == this.GetUserId());
            var tasks = await _dbContext.Events.Where(x =>
                x.Type == Models.EventType.Task &&
                (x.Group!.Id == user.Class.DefaultGroupId || x.Group.Members.Contains(user)) &&
                !x.AssociatedUsers.Contains(user)
            ).Include(x=>x.AttachedFiles).OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).ToArrayAsync();
            var model = new TasksViewModel()
            {
                Tasks = tasks, 
                IsUserAdmin = user.Role == Models.UserRole.Admin,
                UserId = user.Id
            };
            return View(model);
        }

        [HttpGet("{id:guid}/markdone")]
        public async Task<IActionResult> MarkDone(Models.EventId id)
        {
            var ev = await _dbContext.Events.Include(x=>x.AssociatedUsers).FirstAsync(x=>x.Id == id);
            var user = await _dbContext.Users.FirstAsync(x => x.Id == this.GetUserId());
            if (!ev.AssociatedUsers.Contains(user))
            {
                ev.AssociatedUsers.Add(user);
            }
            await _dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

BoroHFR/Views/Shared/_ContributorsPartial.cshtml
<div>
    <h1>Közreműködők</h1>
    <ul>
        <li>Jávor Márton - programozás, ötlet, design</li>
        <li>Varga-Labóczki Vazul - programozás, lelkesedés</li>
    </ul>
    <p>Kapcsolat: <a href="mailto:jmrtn.dev@gmail.com">jmrtn.dev@gmail.com</a></p>
</div>

BoroHFR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BHR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/chat.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BoroHFR.styles.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css"> *@
    <link rel="stylesheet" href="/lib/bootstrap/icons/font/bootstrap-icons.min.css"/>
    <style>
        html,
        body {
            min-height: 100%;
            height: 100%;
        }
    </style>
</head>

<body class="bg-black text-light">
    <div class="wrapper">
    <header  class="page-header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand my-auto" id="logo" asp-controller="Home" asp-action="Index">
                    <img style="height: 30pt;" src="/img/bhrlogo.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" is-active-route asp-controller="Home"
                                asp-action="Index">Főoldal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" is-active-route asp-controller="Tasks"
                                asp-action="Index">Feladatok</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" is-active-route asp-controller="Groups"
                                asp-action="Index">Csevegések</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" is-active-route asp-controller="ButtonGame"
                                asp-action="Index">Gomb</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" is-active-route asp-controller="Admin"
                                   asp-action="Index">Admin</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="dropdown dropdown-dark float-end dropstart">
                    <a style="text-decoration: none;" role="button" id="usermenu" class="dropdown-toggle white-a"
                        data-bs-toggle="dropdown"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                            fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                            <path
                                d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z" />
                        </svg>
                        <span style="text-decoration: underline;">@User.Identity.Name</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-dark">
                        <a class="dropdown-item" href='@Url.Action("Index","Settings")'><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-gear-fill" viewBox="0 0 16 16">
                                <path
                                    d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z" />
                            </svg>Beállítások
                        </a>
                        <a href='@Url.Action("Logout","Authentication")' class="dropdown-item"><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                                <path fill-rule="evenodd"
                                    d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                            </svg>Kijelentkezés
                        </a>
                    </div>

                        </div>
                    </div>
                </nav>
            </header>
		    <main class="page-body">
                <div id="content" class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
		    </main>
            <footer class="page-footer text-center footer text-muted">
                <p class="m-0 p-2">BoroHFR - &copy; 2023-@DateTime.Today.Year Jávor Márton, Varga-Labóczki Vazul, Szabó Tamás</p>
            </footer>
	    </div>

        <div id="chatRoot"></div>

        @await RenderSectionAsync("Modals", required: false)
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/signalr/signalr.min.js"></script>
        <script src="~/js/chat.js"></script>
        <script>

        </script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

BoroHFR/Views/Shared/_PrivacyPolicyModal.cshtml
<div class="modal fade" id="privacypolicymodal" tabindex="-1">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content bg-dark text-light">
            <div class="modal-header">
                <h2>Adatvédelem</h2>
            </div>
            <div class="modal-body">
                <p>Ezt a weboldalt Jávor Márton üzemelteti. (A továbbiakban: "üzemeltető", "mi")</p>
                <p>Ez a szabályzat meghatározza, hogyan kezeljük az Öntől gyűjtött vagy a weboldalunkon keresztül megadott személyes adatokat. Azzal, hogy meglátogatja a BoroHFR weboldalt (ezt a weboldalt), Ön elfogadja és beleegyezik a jelen szabályzatban leírt gyakorlatba.</p>
                <h2>Az Öntől gyűjtött adatok típusai</h2>
                <p>A következő típusú személyes adatokat gyűjthetjük, tárolhatjuk és használhatjuk a weboldalunkat látogató és használó személyekről:</p>
                <ul>
                    <li>Az Ön által megadott információk. Ön a weboldalunkon található űrlapok kitöltésével adhat meg információkat. Ez magában foglalja az Ön által megadott információkat, amikor egy regisztrációs, bejelentkezési, vagy egy feladattal kapcsolatos űrlapot nyújt be. Az Ön által megadott információk közé tartozhat az Ön e-mail címe, osztálya, illetve a csoportok, melyekbe jár.</li>
                </ul>


                <h2>Az adatkezelés időtartama</h2>
                <p>Az adatokat az aktuális tanév időtartama alatt, valamint a tanév lezárulása után 1 hónapig tároljuk, majd töröljük.</p>

                <h2>Hogyan használhatjuk fel az általunk gyűjtött információkat?</h2>
                <p>Az információkat a következő módon használjuk fel:</p>
                <ul>
                    <li>
                        Az Ön által megadott információk. Ezeket az információkat felhasználjuk:
                        <ul>
                            <li>
                                Alapvető funkciók biztosítása.
                            </li>
                            <li>
                                Kapcsolattartás a felhasználóval e-mail-en keresztül.
                            </li>
                        </ul>
                    </li>
                </ul>
                <h2>Az Ön adatainak közzététele</h2>
                <p>Az Ön által megadott bármely információ közvetlenül nekünk kerül elküldésre. Az információkat digitális formában tároljuk, és nem tesszük közzé.</p>

                <h2>Felelősségkizárás</h2>
                <p>
                    Az oldalon megadott adatokért semminemű felelősséget nem vállalunk. A rendszer közösségi felületeire feltöltött tartalmakért minden esetben a felhasználó a felelős, legyen
                    szó érzékeny információról, spamről, vagy egyéb másokat sértő, vagy törvénybe ütköző tartalomról.
                </p>
                <p>
                    A rendszert érő esetleges kibertámadás során kiszivárgó információért, vagy esetleges adatvesztésért a készítők nem vonhatók felelősségre.
                    A rendszer használatával Ön elfogadja, hogy mindent saját felelősségre tölt fel az oldalra.
                </p>

                <h2>Adatok módosítása, törlése, kapcsolatfelvétel</h2>
                <p>Az adatkezelő címe: 2677 Herencsény, Béke u. 20.</p>
                <p>Ön bármikor kérheti adatai módosítását, törlését, vagy az Önről tárolt információk megküldését.</p>
                <p>Ha kérdése van az adatkezeléssel kapcsolatban, vagy szeretne élni az adatkezeléshez kapcsolódó jogaival, vegye fel a kapcsolatot az üzemeltetővel a <a target="_blank" href="mailto:jmrtn.dev@gmail.com">jmrtn.dev@gmail.com</a> e-mail címen.</p>

                <h2>Sütik</h2>
                <p>A weboldal kizárólag a felhasználó jogosultságainak ellenőrzéséhez használ cookie-kat.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bezárás</button>
            </div>
        </div>
    </div>

</div>