BoroHFR/ViewModels/Settings/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BoroHFR.ViewModels.Settings;

public class ChangePasswordViewModel
{
    [Required(ErrorMessage = "Kérlek add meg a jelenlegi jelszavad!")]
    [MinLength(8, ErrorMessage = "A jelszónak minimum 8 karaktert kell tartalmaznia.")]
    [DataType(DataType.Password)] public string OldPassword { get; set; }
    public bool BadPassword { get; set; }
    [Required(ErrorMessage = "Kérlek add meg az új jelszót!")]
    [MinLength(8, ErrorMessage = "A jelszónak minimum 8 karaktert kell tartalmaznia.")]
    [DataType(DataType.Password)]
    public string NewPassword { get; set; }
    [DataType(DataType.Password)]

    [Compare(nameof(NewPassword), ErrorMessage = "A két jelszó nem egyezik.")]
    [Required(ErrorMessage = "Kérlek add meg az új jelszót még egyszer!")]
    public string NewPasswordAgain { get; set; }

    public bool Success { get; set; }
    public string? ErrorMessage { get; set; }
}

BoroHFR/ViewModels/Settings/GroupSettingsViewModel.cs
using BoroHFR.Models;

namespace BoroHFR.ViewModels.Settings;

public class GroupSettingsViewModel
{
    public List<Group> GroupMemberships { get; set; }
}

BoroHFR/ViewModels/Settings/SubjectSearchResultViewModel.cs
using BoroHFR.Models;

namespace BoroHFR.ViewModels.Settings;

public class SubjectSearchResultViewModel
{
    public IEnumerable<Subject> Subjects { get; set; }
}

BoroHFR/ViewModels/Settings/UserDataViewModel.cs
using BoroHFR.Models;

namespace BoroHFR.ViewModels.Settings
{
    public class UserDataViewModel
    {
        public string Username { get; set; }
        public string StorageUsed { get; set; }
        public UserRole Role { get; set; }
        public int EventsCreated { get; set; }
        public int HomeworksDone { get; set; }
        public int EventsAttended { get; set; }
        public DateOnly RegDate { get; set; }
    }
}

BoroHFR/Controllers/Api/UserDataController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BoroHFR.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize("User")]
    public class UserDataController : ControllerBase
    {
        [HttpGet("userid")]
        public IActionResult GetUserId()
        {
            var uid = User.Claims.FirstOrDefault(x=>x.Type=="Id");
            if (uid is null)
            {
                return Unauthorized();
            }
            return Ok(uid.Value);
        }
    }
}

BoroHFR/Controllers/SettingsController.cs
using BoroHFR.Data;
using BoroHFR.Models;
using BoroHFR.ViewModels.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using BoroHFR.Controllers.Helpers;
using Humanizer.Bytes;
using Humanizer;

namespace BoroHFR.Controllers;

[Route("settings")]
[Authorize("User")]
public class SettingsController : Controller
{
    private readonly BoroHfrDbContext _dbContext;

    public SettingsController(BoroHfrDbContext dbConnection)
    {
        _dbContext = dbConnection;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return RedirectToAction("UserData");
    }

    [HttpGet("userdata")]
    public async Task<IActionResult> UserData()
    {
        var user = await _dbContext.Users.FirstOrDefaultAsync(x=>x.Id == this.GetUserId());
        var storage = new ByteSize(await _dbContext.Files.Where(x=>x.Owner == user).SumAsync(x=>x.Size));
        var model = new UserDataViewModel()
        {
            Username = user.Username,
            Role = user.Role,
            RegDate = DateOnly.FromDateTime(user.RegisterTime.Date),
            EventsAttended = await _dbContext.Events.Where(x=>x.Type == EventType.Event && x.AssociatedUsers.Contains(user)).CountAsync(),
            HomeworksDone = await _dbContext.Events.Where(x=>x.Type == EventType.Task && x.AssociatedUsers.Contains(user)).CountAsync(),
            EventsCreated = await _dbContext.Events.Where(x => x.Creator == user).CountAsync(),
            StorageUsed = storage.Humanize()
        };
        return View(model);
    }

    [HttpGet("changepassword")]
    public IActionResult ChangePassword()
    {
        return View();
    }

    [HttpPost("changepassword")]
    public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.Success = false;
        }
        else
        {
            var user = await GetCurrentUserAsync();
            if (BCrypt.Net.BCrypt.EnhancedVerify(model.OldPassword, user.PasswordHash))
            {
                user.PasswordHash = BCrypt.Net.BCrypt.EnhancedHashPassword(model.NewPassword);
                model.Success = true;
                await _dbContext.SaveChangesAsync();
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = "Hibás a jelenlegi jelszó.";
            }
        }
        
        return View(model);
    }

    [HttpGet("groups")]
    public async Task<IActionResult> GroupSettings()
    {
        var user = await GetCurrentUserAsync();
        var model = new GroupSettingsViewModel
        {
            GroupMemberships = await _dbContext.Groups
                .Where(x=>x.Members.Contains(user))
                .Include(g=>g.Subject)
                .ToListAsync()
        };
        return View(model);
    }

    public record SubjectSearchData(string Query);


    [HttpPost("subjectsearch")]
    public async Task<IActionResult> SubjectSearch([FromBody] SubjectSearchData data)
    {
        var user = await GetCurrentUserAsync();
        var subjectsRes = await _dbContext.Subjects
            .Where(x => x.Class == user.Class && x.Groups.Any(y=>!y.Members.Contains(user)) && EF.Functions.Like(x.Name,"%"+data.Query+"%"))
            .Include(sub=>sub.Groups.Where(x => !x.Members.Contains(user))).ToArrayAsync();
        var model = new SubjectSearchResultViewModel() { Subjects = subjectsRes };
        return PartialView("_SubjectSearchPartial", model);
    }

    [HttpGet("joinedgroups")]
    public async Task<IActionResult> JoinedGroups()
    {
        var user = await GetCurrentUserAsync();
        var model = new GroupSettingsViewModel();
        model.GroupMemberships = await _dbContext.Groups
            .Where(x => x.Members.Contains(user))
            .Include(g => g.Subject)
            .ToListAsync();
        return PartialView("_JoinedGroupsPartial", model);

    }

    [HttpGet("joingroup/{id:guid}")]
    public async Task<IActionResult> JoinGroup(GroupId id)
    {
        var user = await GetCurrentUserAsync();
        var group = await _dbContext.Groups
            .Where(x=>x.Subject.Class.Id == user.ClassId && x.Id == id)
            .SingleOrDefaultAsync();
        if (group is null)
        {
            return BadRequest("User cannot join that group.");
        }
        group.Members.Add(user);
        await _dbContext.SaveChangesAsync();
        return Ok();
    }

    [HttpGet("leavegroup/{id:guid}")]
    public async Task<IActionResult> LeaveGroup(GroupId id)
    {
        var user = await GetCurrentUserAsync();
        var group = await _dbContext.Groups
            .Include(g=>g.Members)
            .SingleOrDefaultAsync(x=>x.Id == id);

        if(group is not null)
        {
            group.Members.Remove(user);
            await _dbContext.SaveChangesAsync();
            return Ok();
        }
        
        return BadRequest();
    }


    private async Task<User> GetCurrentUserAsync()
    {
        var id = new UserId(Guid.Parse(User.Claims.Single(x => x.Type == "Id").Value));
        var user = await _dbContext.Users.Include(u=>u.Class).FirstOrDefaultAsync(x=>x.Id==id);
        if (user is null)
        {
            throw new Exception("Current user cannot be found in database.");
        }
        return user;
    }


    public record GroupJoinData(GroupId Id);
}

BoroHFR/Views/Settings/ChangePassword.cshtml
@model BoroHFR.ViewModels.Settings.ChangePasswordViewModel
@{
    Layout = "_SettingsLayout";
}
@using (Html.BeginForm("ChangePassword", "Settings", FormMethod.Post, new { @class = "coolform" }))
{
    <div class="form-group">
    <label>Jelenlegi jelszó:</label>
    @Html.PasswordFor(m=>m.OldPassword, new {@class="form-control bg-dark text-light"})
    @Html.ValidationMessageFor(m=>m.OldPassword,"",new {@class = "text-danger"})
</div>
    <div class="form-group">
    <label>Új jelszó:</label>
    @Html.PasswordFor(m=>m.NewPassword, new {@class="form-control bg-dark text-light"})
    @Html.ValidationMessageFor(m=>m.NewPassword,"",new {@class = "text-danger"})
</div>
    <div class="form-group">
    <label>Új jelszó ismét:</label>
    @Html.PasswordFor(m=>m.NewPasswordAgain, new {@class="form-control bg-dark text-light"})
    @Html.ValidationMessageFor(m=>m.NewPasswordAgain,"",new {@class = "text-danger"})
</div>
    @if (Model?.Success == true)
    {
        <div class="alert alert-success" role="alert">A jelszó megváltozott!</div>
    }
    else if (Model?.ErrorMessage?.Length > 0)
    {
        <div class="alert alert-warning" role="alert">@Model.ErrorMessage</div>
    }
    <button class="btn btn-primary" type="submit">Mentés</button>


}

BoroHFR/Views/Settings/GroupSettings.cshtml
@model BoroHFR.ViewModels.Settings.GroupSettingsViewModel
@{
    Layout = "_SettingsLayout";
}

<div id="joinedgroupscontainer" class="p-3 my-2">
    <h2>Csoportjaid:</h2>
    <div id="joinedgroupslist">
        <partial name="_JoinedGroupsPartial"></partial>
    </div>
</div>


<div class="p-3 my-2">
    <h2>Csoportok keresése</h2>
    <form id="searchform">
        <div class="input-group">
            <input placeholder="Tantárgy neve" class="form-control" id="subjsearch" type="text" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Keresés</button>
            </div>
        </div>



    </form>

</div>


<div id="resultscontainer" class="d-flex flex-column">
    <p class="text-center">Még nincs itt semmi. Keress rá egy tantárgyra!</p>
</div>

@section Scripts{
    <script>
        $("#searchform").submit(x => search(x));

        async function search(sm) {
            sm.preventDefault();
            loadSearchResults();
        }

        function refreshLists() {
            loadSearchResults();
            $("#joinedgroupslist").load('@Url.Action("JoinedGroups")');
        }

        async function loadSearchResults() {
            $("#resultscontainer").html('<span class="spinner-grow spinner-grow-sm mx-auto my-3" role="status" aria-hidden="true"></span>');
            var text = await postData('@Url.Action("SubjectSearch")', { query: $("#subjsearch").val() });
            $("#resultscontainer").html(text);

        }

        async function joinGroup(id) {
            if (!confirm("Biztosan be akarsz lépni ebbe a csoportba?")) {
                return;
            }
            //await postData('@Url.Action("JoinGroup")', { id: id });
            await fetch('/settings/joingroup/' + id);
            await refreshLists();
        }

        async function leaveGroup(id) {
            if (!confirm("Biztosan ki akarsz lépni ebből a csoportból?")) {
                return;
            }
            //await postData('@Url.Action("LeaveGroup")', { id: id });
            await fetch('/settings/leavegroup/' + id);
            await refreshLists();
        }
    </script>
}

BoroHFR/Views/Settings/UserData.cshtml
@model BoroHFR.ViewModels.Settings.UserDataViewModel
@{
    Layout = "_SettingsLayout";
}

<h2>@Model.Username</h2>
<p>
    Információ:
    <ul>
        <li>Regisztráció dátuma: @Model.RegDate</li>
        <li>Rang: @(Model.Role == UserRole.User ? "Felhasználó" : "Adminisztrátor")</li>
        <li>Létrehozott események: @Model.EventsCreated</li>
        <li>Elkészített feladatok: @Model.HomeworksDone</li>
        <li>Események, melyeken részt vett: @Model.EventsAttended</li>
        <li>Felhasznált tárhely: @Model.StorageUsed</li>
    </ul>
</p>

BoroHFR/Views/Settings/_JoinedGroupsPartial.cshtml
@model BoroHFR.ViewModels.Settings.GroupSettingsViewModel
@if (!Model.GroupMemberships.Any())
{
    <p class="text-center text-danger">Egy csoportnak sem vagy tagja.</p>
}
@foreach (var group in Model.GroupMemberships)
{
    <div class="row">
        <div class="col d-flex align-items-center">
            <p class="m-0 text-truncate">
                @group.Subject.Name - @group.Name (@group.Teacher)
            </p>


        </div>
        <div class="col-2">
            <button class="btn btn-outline-danger" onclick="leaveGroup('@group.Id')">Kilépés</button>
        </div>
    </div>
}

BoroHFR/Views/Settings/_SettingsLayout.cshtml
@{
    Layout = "_Layout";
}
<h1>Beállítások</h1>
<div class="row">
    <ul class="nav nav-pills flex-sm-column col-sm-3">
        <li class="nav-item"><a is-active-route class='nav-link' asp-controller="Settings"
                asp-action="UserData">Fiókbeállítások</a></li>
        <li class="nav-item"><a is-active-route class='nav-link' asp-controller="Settings"
                asp-action="ChangePassword">Jelszó
                módosítása</a></li>
        <li class="nav-item"><a is-active-route class='nav-link' asp-controller="Settings"
                asp-action="GroupSettings">Csoportbeállítások</a></li>
    </ul>
    <div class="offset-sm-1 col-sm-8">
        @RenderBody()
    </div>
</div>

@section Scripts {
    @await RenderSectionAsync("Scripts",required: false)
}

BoroHFR/Views/Settings/_SubjectSearchPartial.cshtml
@model BoroHFR.ViewModels.Settings.SubjectSearchResultViewModel
@{
    int row = 0;
}

@if (!Model.Subjects.Any())
{
    <p class="text-danger text-center">Nincs találat. Lehet, hogy már csatlakoztál?</p>
}

<style>
    .acc-btn {
        background-color: rgb(33, 37, 41) !important;
        color: white !important;
    }

    .acc-btn.collapsed i {
        transform: rotate(0deg);
    }

    .acc-btn i {
        transform: rotate(180deg);
    }
</style>
<div class="accordion accordion-flush" id="subjectsAccordion">


    @foreach (var subject in Model.Subjects)
    {
        <div class="accordion-item  text-light bg-dark">
            <h2 class="accordion-header" id='@("heading"+subject.Id)'>
                <button class="acc-btn collapsed w-100 h-100 text-start" type="button" data-bs-toggle="collapse"
                        data-bs-target='@("#collapse" + subject.Id)' aria-expanded="false"
                        aria-controls='@("collapse"+subject.Id)'>
                    <span>@subject.Name </span> <i class="bi bi-chevron-down float-end"></i>
                </button>
            </h2>
            <div id='@("collapse"+subject.Id)' class="accordion-collapse collapse" aria-labelledby='@("heading"+subject.Id)'
                data-bs-parent="#subjectsAccordion">
                <div class="accordion-body">
                    @foreach (var group in subject.Groups)
                    {
                        <div class="row d-flex">
                            <div class="col my-auto">
                                @group.Name (@group.Teacher)
                            </div>
                            <div class="col-4">
                                <button class="btn btn-primary float-end" onclick="joinGroup('@group.Id')">Csatlakozás</button>
                            </div>
                        </div>
                    }


                </div>
            </div>
        </div>
        row++;
    }
</div>